name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.6
      - run: corepack enable
      - run: yarn upgrade
      - run: yarn set version self
      - run: yarn install --immutable
      - run: yarn install -g -U @lhci/cli@0.14.x
      - run: yarn npm audit fix
      - run: yarn run build
      - run: lhci autorun
